// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'DEPRECATED',
    appId: '1:442498757028:web:00beda08d3df98edf39131',
    messagingSenderId: '442498757028',
    projectId: 'designer-375bd',
    authDomain: 'designer-375bd.firebaseapp.com',
    storageBucket: 'designer-375bd.firebasestorage.app',
    measurementId: 'G-TFNPHH26WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'DEPRECATED',
    appId: '1:442498757028:android:f436d451c978d06ef39131',
    messagingSenderId: '442498757028',
    projectId: 'designer-375bd',
    storageBucket: 'designer-375bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'DEPRECATED',
    appId: '1:442498757028:ios:af9bf018de76a291f39131',
    messagingSenderId: '442498757028',
    projectId: 'designer-375bd',
    storageBucket: 'designer-375bd.firebasestorage.app',
    iosBundleId: 'com.example.artitecture_design',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'DEPRECATED',
    appId: '1:442498757028:ios:af9bf018de76a291f39131',
    messagingSenderId: '442498757028',
    projectId: 'designer-375bd',
    storageBucket: 'designer-375bd.firebasestorage.app',
    iosBundleId: 'com.example.artitecture_design',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'DEPRECATED',
    appId: '1:442498757028:web:ba9e7bca3032cbdbf39131',
    messagingSenderId: '442498757028',
    projectId: 'designer-375bd',
    authDomain: 'designer-375bd.firebaseapp.com',
    storageBucket: 'designer-375bd.firebasestorage.app',
    measurementId: 'G-MH86PKRX9T',
  );
}
